version: "3"

services:
  nginx:
    image: nginx:1.15
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - custom_network
    depends_on:
      - app
  app:
    build:
      context: ./src
      args:
        - APIKEY=${APIKEY}
        - APISECRET=${APISECRET}
        - AUTHORIZATIONHEADER=${AUTHORIZATIONHEADER}
        - DB_USERNAME=${DB_USERNAME}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_SERVER_NAME=${DB_SERVER_NAME}
        - DB_DATABASE_NAME=${DB_DATABASE_NAME}
        - PORT=${PORT}
    ports:
      - "5000:5000"
    command: gunicorn --bind 0.0.0.0:8000 --workers 4 "app.create_app:create_app()"
    depends_on:
      - db
    volumes:
      - ./:/var/www
    networks:
      custom_network:
        aliases:
          - flask-app

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - custom_network

networks:
  custom_network:

volumes:
  pg_data:
