version: "3"

services:
  app:
    build:
      context: ./Data
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - custom_network
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - custom_network

networks:
  custom_network:

volumes:
  pg_data:
