version: "3"

services:
  fuel_DB:
    image: postgres:14
    container_name: fuel_DB
    env_file:
      - .env
    ports: 
        - 5433:5432
  fuel_etl_project:
    image: nsw-fuel-etl:1.8
    depends_on:
      - fuel_DB
    env_file:
      - .env

# networks:
#   custom_network:

# volumes:
#   pg_data:
