version: "3"

services:
  app:
    build:
      context: ./src
      args:
        - APIKEY=${APIKEY}
        - APISECRET=${APISECRET}
        - AUTHORIZATIONHEADER=${AUTHORIZATIONHEADER}
        - DB_USERNAME=${DB_USERNAME}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_SERVER_NAME=${DB_SERVER_NAME}
        - DB_DATABASE_NAME=${DB_DATABASE_NAME}
        - PORT=${PORT}
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - custom_network
    restart: always

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - custom_network

networks:
  custom_network:

volumes:
  pg_data:
