name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Docker Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 444987252577.dkr.ecr.us-east-1.amazonaws.com

      - name: Build Docker image for app service
        run: docker-compose -f docker-compose.yml build app

      - name: Push Docker image to ECR for app service
        run: |
          docker tag data-engineer-camp-project-1-app:latest 444987252577.dkr.ecr.us-east-1.amazonaws.com/project1:latest
          docker push 444987252577.dkr.ecr.us-east-1.amazonaws.com/project1:latest
