name: Deploy to AWS ECS

on:
  push:
    branches:
      - feature/docker-yang

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region <AWS_REGION> | docker login --username AWS --password-stdin <AWS_ACCOUNT_ID>.dkr.ecr.<AWS_REGION>.amazonaws.com
        env:
          AWS_REGION: us-east-1  # Replace with your AWS region
          AWS_ACCOUNT_ID: 123456789012  # Replace with your AWS account ID

      - name: Pull Docker image
        run: docker pull <AWS_ACCOUNT_ID>.dkr.ecr.<AWS_REGION>.amazonaws.com/<YOUR_IMAGE_NAME>:<TAG>
        env:
          AWS_REGION: us-east-1  # Replace with your AWS region
          AWS_ACCOUNT_ID: 123456789012  # Replace with your AWS account ID
          YOUR_IMAGE_NAME: my-docker-app  # Replace with your Docker image name
          TAG: latest  # Replace with the image tag

      - name: Deploy to AWS ECS
        run: |
          aws ecs update-service --cluster <ECS_CLUSTER_NAME> --service <ECS_SERVICE_NAME> --force-new-deployment
        env:
          AWS_REGION: us-east-1  # Replace with your AWS region
          ECS_CLUSTER_NAME: my-ecs-cluster  # Replace with your ECS cluster name
          ECS_SERVICE_NAME: my-ecs-service  # Replace with your ECS service name
